### ISSUE TITLE
Zoom in and out using two fingers doesn't work

### ISSUE THREAD

**Issue by ksawerykarwacki** [Oromis/touch20#9]
I installed extension from chrome store and I am unable to zoom in/out.

I'm using Edge Chromium Version 81.0.416.68 (Official build) (64-bit) on Surface Pro 7

**Comment by Oromis** [comment]
Thanks for the report, I'll have a look at this today or tomorrow. Does it work in Chrome?

**Comment by Oromis** [comment]
Fixed in the latest version (v1.3.0). Make sure to set "Use scroll to Zoom" in your settings.
